### ISSUE TITLE
Problems using the 0.0.3.6 with Windows 8.1

### ISSUE THREAD

**Issue by RamonAcevedo** [jochenwierum/openvpn-manager#23]
Dear all,

I had Windows 8, and I upgraded  to Windows 8.1, after the upgrade everything worked fine but your OpenVPN Manager application. I am not able to use it any more. Would it be possible to provideme with some instructions on what to do , so I can continue to use it. The message I get is: "error while starting OpenVPN" . Thanks in advance for your help.

**Comment by hapm** [comment]
Is this still an issue? I have no problems here on Win 8.1 and Win 10. Do you have the option to show details? Is there a log file you can attach?

**Comment by hapm** [comment]
This will be closed. Can not reproduce with version 0.0.3.8.
