### ISSUE TITLE
openvpn-manager autoconnect

### ISSUE THREAD

**Issue by julicravo** [jochenwierum/openvpn-manager#34]
Hello
I'm using version 3.6, and only one certificate.

I would like to connect to vpn to start windows.

The openvpnmanager service is active.

Currently the process is done manual -> right and connect button.

I appreciate all help.

Follow the .ovpn file:

dev tun
persist-tun
persist-key
cipher BF-CBC
auth SHA1
tls-client
client
resolv-retry infinite
remote ip 1194 udp
lport 0
verify-x509-name "server" name
pkcs12 srvlmssafw01-udp-1194-XXX.p12
comp-lzo

# dont terminate service process on wrong password, ask again
auth-retry interact
# open management channel
management 127.0.0.1 166
# wait for management to explicitly start connection
management-hold
# query management channel for user/pass
management-query-passwords
# disconnect VPN when management program connection is closed
management-signal
# forget password when management disconnects
management-forget-disconnect

**Comment by hapm** [comment]
This is the same as in #12
