### ISSUE TITLE
Windows 10 problem after Return from Hibernate

### ISSUE THREAD

**Issue by kkomara** [jochenwierum/openvpn-manager#35]
I use Hibernate allot !!  If I connect to my home openvpn server and connect with OpenVPN Manager it works just fine - and shows green in icon bar.  If I then hibernate my tablet then un-hibernate it - status is still green. Cannot disconnect or do anything with icon.  OpenVPN connection is NOT up.  Either have to restart Tablet OR Kill OpenVPN Manager program - stop and start the OpenVPN manager service and restart the OpenVPN Manager program.

Is this a known issue ??

**Comment by hapm** [comment]
Do you use the openvpn bundled service or the one that comes with openvpnmanager? Can you provide a log from after resuming from hibernate? Please remove sensible data from the logs where needed.

**Comment by hapm** [comment]
Can't reproduce without proper information. Feel free to reopen when you can provide more information on this issue.
