### ISSUE TITLE
Reason for targeting x86?

### ISSUE THREAD

**Issue by hapm** [jochenwierum/openvpn-manager#37]
Is there any reason why some of the assemblies target x86 only? As we don't reference any unmanaged x86 libraries, we should change this to AnyCPU to give the .net runtime the choice.

Or do we want to save memory, by forcing the runtime into 32bit? If so, I suggest to only compile the executables as x86 and let the dlls target AnyCPU anyway.

**Comment by jochenwierum** [comment]
There is absolutely no reason for this :) We should use AnyCPU here.
