### ISSUE TITLE
OpenVPN manager service not starting on Windows 10

### ISSUE THREAD

**Issue by ttblum** [jochenwierum/openvpn-manager#45]
Hello,

I have several Win10 machines where the machine boots up but the 'OpenVPN Manager' never starts.  I'm not able to connect to any VPNs with Openvpn-Manager until I manually start the 'OpenVPN Manager' service.  So far I can't find any errors or other clues as to why this isn't starting.

Has anyone else had this issue?

**Comment by ttblum** [comment]
On this particular workstation I uninstalled an expired McAfee antivirus that was on there.  'OpenVPN Manager' service now starts OK every time on bootup.

**Comment by hapm** [comment]
Would be interesting to know if there is some log from McAfee claiming OpnVPNManager to be a malicious program. There was a time were anti virus software reported OpenVPNManager by heurisitics. It was a false positive and I'm not aware of any newer versions of the software still report OpenVPNManager to be a bad thing, but it is possible that it gets blocked by old versions of anti virus software.
